# Generated by Django 4.1.7 on 2023-04-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время посещения'),
        ),
    ]
